WebAuction/Models/Lot.cs
namespace WebAuction.Models
{
    public class Lot
    {
        public int Id { get; set; } = 0;
        public string Title { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public float BuyOutPrice { get; set; } = 0f;
        public float StartPrice { get; set; } = 0f;
        public float Bet { get; set; } = 0f;
    }
}

WebAuction/Controllers/AuctionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using System.Xml.Serialization;
using Newtonsoft.Json;
using WebAuction.Models;

namespace WebAuction.Controllers
{
    public class AuctionController : Controller
    {
        private string _baseAddress = "http://localhost:65322/Auction.svc/";

        // GET: Auction
        public ActionResult Index()
        {
            return View();
        }

        // GET: Auction
        public async Task<ActionResult> AllLots()
        {
            List<Lot> lots = new List<Lot>();

            using (HttpClient httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri(_baseAddress);
                httpClient.DefaultRequestHeaders.Clear();
                httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await httpClient.GetAsync("alllots");

                if (response.IsSuccessStatusCode)
                {
                    var result = response.Content.ReadAsStringAsync().Result;
                    //StringReader reader = new StringReader(result);
                    //XmlSerializer serializer = new XmlSerializer(typeof(List<Lot>));
                    //lots = (List<Lot>)serializer.Deserialize(reader);
                    lots = JsonConvert.DeserializeObject<List<Lot>>(result);
                }

                return View(lots);
            }

        }

        // GET: Auction
        public async Task<ActionResult> Lot(int? id)
        {
            Lot lot = new Lot();

            using (HttpClient httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri(_baseAddress);
                httpClient.DefaultRequestHeaders.Clear();
                httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await httpClient.GetAsync("alllots/" + id);

                if (response.IsSuccessStatusCode)
                {
                    var result = response.Content.ReadAsStringAsync().Result;
                    //StringReader reader = new StringReader(result);
                    //XmlSerializer serializer = new XmlSerializer(typeof(Lot));
                    //lots = (List<Lot>)serializer.Deserialize(reader);
                    lot = JsonConvert.DeserializeObject<Lot>(result);
                }

            }
            return View(lot);
        }

        public async Task<ActionResult> PlaceBet(Lot lot)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri(_baseAddress);
                var sendLot = JsonConvert.SerializeObject(lot);
                HttpContent content = new StringContent(sendLot, System.Text.Encoding.UTF8, "application/json");
                var res = await httpClient.PutAsync("/Auction.svc/alllots/" + lot.Id, content);

                Debug.WriteLine("!!!!!!!!!!!!!!!!!!!!!!" + res.Content.ReadAsStringAsync().Result);
            }
            return View("Index");
        }


        public ActionResult Create()
        {

            return View();
        }

        public async Task<ActionResult> CreateForm(Lot lot)
        {
            using (HttpClient httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri(_baseAddress);
                var sendLot = JsonConvert.SerializeObject(lot);
                HttpContent content = new StringContent(sendLot, System.Text.Encoding.UTF8, "application/json");
                var res = await httpClient.PutAsync("/Auction.svc/alllots", content);

                //Debug.WriteLine("!!!!!!!!!!!!!!!!!!!!!!" + res.Content.ReadAsStringAsync().Result);
            }
            return View("Index");
        }
    }
}

WebAuction/Views/Auction/AllLots.cshtml
@model IEnumerable<WebAuction.Models.Lot>

@{
    ViewBag.Title = "AllLots";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>All Lots</h2>

<p>
    @Html.ActionLink("Add lot", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BuyOutPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bet)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BuyOutPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bet)
            </td>
            <td>
                @Html.ActionLink("Details", "Lot", new {id = item.Id}) |
            </td>
        </tr>
    }

</table>

WebAuction/Views/Auction/Create.cshtml
@model WebAuction.Models.Lot

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("CreateForm", "Auction", FormMethod.Post, new {@class = "form-horizontal", role = "form"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Lot</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Id, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Id, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BuyOutPrice, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.BuyOutPrice, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.BuyOutPrice, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartPrice, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartPrice, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.StartPrice, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bet, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bet, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Bet, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebAuction/Views/Auction/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Welcome</h2>

WebAuction/Views/Auction/Lot.cshtml
@model WebAuction.Models.Lot

@{
    ViewBag.Title = "Lot";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lot</h2>

<div>
    <h4>Lot</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BuyOutPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BuyOutPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bet)
        </dd>

    </dl>
</div>
<p>
    @using (Html.BeginForm("PlaceBet", "Auction", FormMethod.Post, new {@class = "form-horizontal", role = "form"}))
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Bet, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bet, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Bet, "", new {@class = "text-danger"})
            </div>
        </div>
        @Html.HiddenFor(m => m.Id)
        @Html.HiddenFor(m => m.BuyOutPrice)
        @Html.HiddenFor(m => m.StartPrice)
        @Html.HiddenFor(m => m.Description)
        @Html.HiddenFor(m => m.Title)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Bet" class="btn btn-default"/>
            </div>
        </div>
    }
</p>
<p>
    @Html.ActionLink("Back to List", "AllLots")
</p>

WebAuction/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Generic auction", "Index", "Auction", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("All lots", "AllLots", "Auction")</li>
            </ul>
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>